# Generated by Django 6.0.3 on 2026-05-13 13:24

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('log', 'Logged a book'), ('review', 'Reviewed a book'), ('follow', 'Followed a user'), ('shelf', 'Added to shelf')], max_length=20)),
                ('content_id', models.CharField(blank=True, max_length=120)),
                ('content_type_label', models.CharField(blank=True, max_length=50)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='api.book')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_activit_user_id_3893a3_idx'), models.Index(fields=['activity_type', '-created_at'], name='api_activit_activit_09e732_idx')],
            },
        ),
    ]
